export enum RenderHintsDataType {
    Country = "Country",
    DataURL = "DataURL",
    EMailAddress = "EMailAddress",
    HEXColor = "HEXColor",
    Language = "Language",
    PhoneNumber = "PhoneNumber",
    URL = "URL",
    FileReference = "FileReference",
    Date = "Date",
    DatePeriod = "DatePeriod",
    DateTime = "DateTime",
    DateTimePeriod = "DateTimePeriod",
    Time = "Time",
    TimePeriod = "TimePeriod",
    Day = "Day",
    Month = "Month",
    Year = "Year",
    XML = "XML"
}
