export enum CountryAlpha2 {
    AF = "AF",
    AL = "AL",
    AS = "AS",
    AD = "AD",
    AO = "AO",
    AI = "AI",
    AQ = "AQ",
    AG = "AG",
    AR = "AR",
    AM = "AM",
    AW = "AW",
    AU = "AU",
    AT = "AT",
    AZ = "AZ",
    AE = "AE",
    AX = "AX",
    BS = "BS",
    BH = "BH",
    BD = "BD",
    BB = "BB",
    BY = "BY",
    BE = "BE",
    BZ = "BZ",
    BJ = "BJ",
    BM = "BM",
    BT = "BT",
    BO = "BO",
    BQ = "BQ",
    BA = "BA",
    BW = "BW",
    BV = "BV",
    BR = "BR",
    BN = "BN",
    BG = "BG",
    BF = "BF",
    BI = "BI",
    BL = "BL",
    CV = "CV",
    CM = "CM",
    CA = "CA",
    CF = "CF",
    CL = "CL",
    CN = "CN",
    CX = "CX",
    CC = "CC",
    CO = "CO",
    CD = "CD",
    CG = "CG",
    CK = "CK",
    CR = "CR",
    CU = "CU",
    CW = "CW",
    CY = "CY",
    CZ = "CZ",
    CI = "CI",
    CH = "CH",
    DZ = "DZ",
    DK = "DK",
    DJ = "DJ",
    DM = "DM",
    DO = "DO",
    DE = "DE",
    EC = "EC",
    EG = "EG",
    ER = "ER",
    EE = "EE",
    ET = "ET",
    ES = "ES",
    EH = "EH",
    FK = "FK",
    FO = "FO",
    FJ = "FJ",
    FI = "FI",
    FR = "FR",
    FM = "FM",
    GQ = "GQ",
    GF = "GF",
    GA = "GA",
    GM = "GM",
    GE = "GE",
    GH = "GH",
    GI = "GI",
    GR = "GR",
    GL = "GL",
    GD = "GD",
    GP = "GP",
    GU = "GU",
    GT = "GT",
    GG = "GG",
    GN = "GN",
    GW = "GW",
    GY = "GY",
    GS = "GS",
    GB = "GB",
    HR = "HR",
    HT = "HT",
    HM = "HM",
    HN = "HN",
    HK = "HK",
    HU = "HU",
    IO = "IO",
    IS = "IS",
    IN = "IN",
    ID = "ID",
    IR = "IR",
    IQ = "IQ",
    IE = "IE",
    IM = "IM",
    IL = "IL",
    IT = "IT",
    JM = "JM",
    JP = "JP",
    JE = "JE",
    JO = "JO",
    KH = "KH",
    KY = "KY",
    KM = "KM",
    KZ = "KZ",
    KE = "KE",
    KI = "KI",
    KP = "KP",
    KR = "KR",
    KW = "KW",
    KG = "KG",
    KN = "KN",
    LA = "LA",
    LV = "LV",
    LB = "LB",
    LS = "LS",
    LR = "LR",
    LY = "LY",
    LI = "LI",
    LT = "LT",
    LU = "LU",
    LC = "LC",
    LK = "LK",
    MO = "MO",
    MG = "MG",
    MW = "MW",
    MY = "MY",
    MV = "MV",
    ML = "ML",
    MT = "MT",
    MH = "MH",
    MQ = "MQ",
    MR = "MR",
    MU = "MU",
    MX = "MX",
    MD = "MD",
    MC = "MC",
    MN = "MN",
    ME = "ME",
    MS = "MS",
    MA = "MA",
    MZ = "MZ",
    MM = "MM",
    MP = "MP",
    MK = "MK",
    MF = "MF",
    NA = "NA",
    NR = "NR",
    NP = "NP",
    NL = "NL",
    NC = "NC",
    NZ = "NZ",
    NI = "NI",
    NE = "NE",
    NG = "NG",
    NU = "NU",
    NF = "NF",
    NO = "NO",
    OM = "OM",
    PF = "PF",
    PK = "PK",
    PW = "PW",
    PS = "PS",
    PA = "PA",
    PG = "PG",
    PY = "PY",
    PE = "PE",
    PH = "PH",
    PN = "PN",
    PL = "PL",
    PT = "PT",
    PR = "PR",
    PM = "PM",
    QA = "QA",
    RO = "RO",
    RU = "RU",
    RW = "RW",
    RE = "RE",
    RS = "RS",
    SV = "SV",
    SZ = "SZ",
    SH = "SH",
    SM = "SM",
    ST = "ST",
    SA = "SA",
    SN = "SN",
    SC = "SC",
    SL = "SL",
    SG = "SG",
    SX = "SX",
    SK = "SK",
    SI = "SI",
    SB = "SB",
    SO = "SO",
    SS = "SS",
    SD = "SD",
    SR = "SR",
    SJ = "SJ",
    SE = "SE",
    SY = "SY",
    TD = "TD",
    TF = "TF",
    TW = "TW",
    TJ = "TJ",
    TZ = "TZ",
    TH = "TH",
    TL = "TL",
    TG = "TG",
    TK = "TK",
    TO = "TO",
    TT = "TT",
    TN = "TN",
    TR = "TR",
    TM = "TM",
    TC = "TC",
    TV = "TV",
    UG = "UG",
    UA = "UA",
    UM = "UM",
    US = "US",
    UY = "UY",
    UZ = "UZ",
    VA = "VA",
    VC = "VC",
    VU = "VU",
    VE = "VE",
    VN = "VN",
    VG = "VG",
    VI = "VI",
    WS = "WS",
    WF = "WF",
    YT = "YT",
    YE = "YE",
    ZA = "ZA",
    ZM = "ZM",
    ZW = "ZW"
}

export const COUNTRIES_ALPHA2_TO_ENGLISH_NAME = new Map<CountryAlpha2, string>([
    [CountryAlpha2.AD, "Andorra"],
    [CountryAlpha2.AE, "United Arab Emirates (the)"],
    [CountryAlpha2.AF, "Afghanistan"],
    [CountryAlpha2.AG, "Antigua and Barbuda"],
    [CountryAlpha2.AI, "Anguilla"],
    [CountryAlpha2.AL, "Albania"],
    [CountryAlpha2.AM, "Armenia"],
    [CountryAlpha2.AO, "Angola"],
    [CountryAlpha2.AQ, "Antarctica"],
    [CountryAlpha2.AR, "Argentina"],
    [CountryAlpha2.AS, "American Samoa"],
    [CountryAlpha2.AT, "Austria"],
    [CountryAlpha2.AU, "Australia"],
    [CountryAlpha2.AW, "Aruba"],
    [CountryAlpha2.AX, "Åland Islands"],
    [CountryAlpha2.AZ, "Azerbaijan"],
    [CountryAlpha2.BA, "Bosnia and Herzegovina"],
    [CountryAlpha2.BB, "Barbados"],
    [CountryAlpha2.BD, "Bangladesh"],
    [CountryAlpha2.BE, "Belgium"],
    [CountryAlpha2.BF, "Burkina Faso"],
    [CountryAlpha2.BG, "Bulgaria"],
    [CountryAlpha2.BH, "Bahrain"],
    [CountryAlpha2.BI, "Burundi"],
    [CountryAlpha2.BJ, "Benin"],
    [CountryAlpha2.BL, "Saint Barthélemy"],
    [CountryAlpha2.BM, "Bermuda"],
    [CountryAlpha2.BN, "Brunei Darussalam"],
    [CountryAlpha2.BO, "Bolivia (Plurinational State of)"],
    [CountryAlpha2.BQ, "Bonaire, Sint Eustatius and Saba"],
    [CountryAlpha2.BR, "Brazil"],
    [CountryAlpha2.BS, "Bahamas (the)"],
    [CountryAlpha2.BT, "Bhutan"],
    [CountryAlpha2.BV, "Bouvet Island"],
    [CountryAlpha2.BW, "Botswana"],
    [CountryAlpha2.BY, "Belarus"],
    [CountryAlpha2.BZ, "Belize"],
    [CountryAlpha2.CA, "Canada"],
    [CountryAlpha2.CC, "Cocos (Keeling) Islands (the)"],
    [CountryAlpha2.CD, "Congo (the Democratic Republic of the)"],
    [CountryAlpha2.CF, "Central African Republic (the)"],
    [CountryAlpha2.CG, "Congo (the)"],
    [CountryAlpha2.CH, "Switzerland"],
    [CountryAlpha2.CI, "Côte d'Ivoire"],
    [CountryAlpha2.CK, "Cook Islands (the)"],
    [CountryAlpha2.CL, "Chile"],
    [CountryAlpha2.CM, "Cameroon"],
    [CountryAlpha2.CN, "China"],
    [CountryAlpha2.CO, "Colombia"],
    [CountryAlpha2.CR, "Costa Rica"],
    [CountryAlpha2.CU, "Cuba"],
    [CountryAlpha2.CV, "Cabo Verde"],
    [CountryAlpha2.CW, "Curaçao"],
    [CountryAlpha2.CX, "Christmas Island"],
    [CountryAlpha2.CY, "Cyprus"],
    [CountryAlpha2.CZ, "Czechia"],
    [CountryAlpha2.DE, "Germany"],
    [CountryAlpha2.DJ, "Djibouti"],
    [CountryAlpha2.DK, "Denmark"],
    [CountryAlpha2.DM, "Dominica"],
    [CountryAlpha2.DO, "Dominican Republic (the)"],
    [CountryAlpha2.DZ, "Algeria"],
    [CountryAlpha2.EC, "Ecuador"],
    [CountryAlpha2.EE, "Estonia"],
    [CountryAlpha2.EG, "Egypt"],
    [CountryAlpha2.EH, "Western Sahara"],
    [CountryAlpha2.ER, "Eritrea"],
    [CountryAlpha2.ES, "Spain"],
    [CountryAlpha2.ET, "Ethiopia"],
    [CountryAlpha2.FI, "Finland"],
    [CountryAlpha2.FJ, "Fiji"],
    [CountryAlpha2.FK, "Falkland Islands (the) [Malvinas]"],
    [CountryAlpha2.FM, "Micronesia (Federated States of)"],
    [CountryAlpha2.FO, "Faroe Islands (the)"],
    [CountryAlpha2.FR, "France"],
    [CountryAlpha2.GA, "Gabon"],
    [CountryAlpha2.GB, "United Kingdom of Great Britain and Northern Ireland (the)"],
    [CountryAlpha2.GD, "Grenada"],
    [CountryAlpha2.GE, "Georgia"],
    [CountryAlpha2.GF, "French Guiana"],
    [CountryAlpha2.GG, "Guernsey"],
    [CountryAlpha2.GH, "Ghana"],
    [CountryAlpha2.GI, "Gibraltar"],
    [CountryAlpha2.GL, "Greenland"],
    [CountryAlpha2.GM, "Gambia (the)"],
    [CountryAlpha2.GN, "Guinea"],
    [CountryAlpha2.GP, "Guadeloupe"],
    [CountryAlpha2.GQ, "Equatorial Guinea"],
    [CountryAlpha2.GR, "Greece"],
    [CountryAlpha2.GS, "South Georgia and the South Sandwich Islands"],
    [CountryAlpha2.GT, "Guatemala"],
    [CountryAlpha2.GU, "Guam"],
    [CountryAlpha2.GW, "Guinea-Bissau"],
    [CountryAlpha2.GY, "Guyana"],
    [CountryAlpha2.HK, "Hong Kong"],
    [CountryAlpha2.HM, "Heard Island and McDonald Islands"],
    [CountryAlpha2.HN, "Honduras"],
    [CountryAlpha2.HR, "Croatia"],
    [CountryAlpha2.HT, "Haiti"],
    [CountryAlpha2.HU, "Hungary"],
    [CountryAlpha2.ID, "Indonesia"],
    [CountryAlpha2.IE, "Ireland"],
    [CountryAlpha2.IL, "Israel"],
    [CountryAlpha2.IM, "Isle of Man"],
    [CountryAlpha2.IN, "India"],
    [CountryAlpha2.IO, "British Indian Ocean Territory (the)"],
    [CountryAlpha2.IQ, "Iraq"],
    [CountryAlpha2.IR, "Iran (Islamic Republic of)"],
    [CountryAlpha2.IS, "Iceland"],
    [CountryAlpha2.IT, "Italy"],
    [CountryAlpha2.JE, "Jersey"],
    [CountryAlpha2.JM, "Jamaica"],
    [CountryAlpha2.JO, "Jordan"],
    [CountryAlpha2.JP, "Japan"],
    [CountryAlpha2.KE, "Kenya"],
    [CountryAlpha2.KG, "Kyrgyzstan"],
    [CountryAlpha2.KH, "Cambodia"],
    [CountryAlpha2.KI, "Kiribati"],
    [CountryAlpha2.KM, "Comoros (the)"],
    [CountryAlpha2.KN, "Saint Kitts and Nevis"],
    [CountryAlpha2.KP, "Korea (the Democratic People's Republic of)"],
    [CountryAlpha2.KR, "Korea (the Republic of)"],
    [CountryAlpha2.KW, "Kuwait"],
    [CountryAlpha2.KY, "Cayman Islands (the)"],
    [CountryAlpha2.KZ, "Kazakhstan"],
    [CountryAlpha2.LA, "Lao People's Democratic Republic (the)"],
    [CountryAlpha2.LB, "Lebanon"],
    [CountryAlpha2.LC, "Saint Lucia"],
    [CountryAlpha2.LI, "Liechtenstein"],
    [CountryAlpha2.LK, "Sri Lanka"],
    [CountryAlpha2.LR, "Liberia"],
    [CountryAlpha2.LS, "Lesotho"],
    [CountryAlpha2.LT, "Lithuania"],
    [CountryAlpha2.LU, "Luxembourg"],
    [CountryAlpha2.LV, "Latvia"],
    [CountryAlpha2.LY, "Libya"],
    [CountryAlpha2.MA, "Morocco"],
    [CountryAlpha2.MC, "Monaco"],
    [CountryAlpha2.MD, "Moldova (the Republic of)"],
    [CountryAlpha2.ME, "Montenegro"],
    [CountryAlpha2.MF, "Saint Martin (French part)"],
    [CountryAlpha2.MG, "Madagascar"],
    [CountryAlpha2.MH, "Marshall Islands (the)"],
    [CountryAlpha2.MK, "Republic of North Macedonia"],
    [CountryAlpha2.ML, "Mali"],
    [CountryAlpha2.MM, "Myanmar"],
    [CountryAlpha2.MN, "Mongolia"],
    [CountryAlpha2.MO, "Macao"],
    [CountryAlpha2.MP, "Northern Mariana Islands (the)"],
    [CountryAlpha2.MQ, "Martinique"],
    [CountryAlpha2.MR, "Mauritania"],
    [CountryAlpha2.MS, "Montserrat"],
    [CountryAlpha2.MT, "Malta"],
    [CountryAlpha2.MU, "Mauritius"],
    [CountryAlpha2.MV, "Maldives"],
    [CountryAlpha2.MW, "Malawi"],
    [CountryAlpha2.MX, "Mexico"],
    [CountryAlpha2.MY, "Malaysia"],
    [CountryAlpha2.MZ, "Mozambique"],
    [CountryAlpha2.NA, "Namibia"],
    [CountryAlpha2.NC, "New Caledonia"],
    [CountryAlpha2.NE, "Niger (the)"],
    [CountryAlpha2.NF, "Norfolk Island"],
    [CountryAlpha2.NG, "Nigeria"],
    [CountryAlpha2.NI, "Nicaragua"],
    [CountryAlpha2.NL, "Netherlands (the)"],
    [CountryAlpha2.NO, "Norway"],
    [CountryAlpha2.NP, "Nepal"],
    [CountryAlpha2.NR, "Nauru"],
    [CountryAlpha2.NU, "Niue"],
    [CountryAlpha2.NZ, "New Zealand"],
    [CountryAlpha2.OM, "Oman"],
    [CountryAlpha2.PA, "Panama"],
    [CountryAlpha2.PE, "Peru"],
    [CountryAlpha2.PF, "French Polynesia"],
    [CountryAlpha2.PG, "Papua New Guinea"],
    [CountryAlpha2.PH, "Philippines (the)"],
    [CountryAlpha2.PK, "Pakistan"],
    [CountryAlpha2.PL, "Poland"],
    [CountryAlpha2.PM, "Saint Pierre and Miquelon"],
    [CountryAlpha2.PN, "Pitcairn"],
    [CountryAlpha2.PR, "Puerto Rico"],
    [CountryAlpha2.PS, "Palestine, State of"],
    [CountryAlpha2.PT, "Portugal"],
    [CountryAlpha2.PW, "Palau"],
    [CountryAlpha2.PY, "Paraguay"],
    [CountryAlpha2.QA, "Qatar"],
    [CountryAlpha2.RE, "Réunion"],
    [CountryAlpha2.RO, "Romania"],
    [CountryAlpha2.RS, "Serbia"],
    [CountryAlpha2.RU, "Russian Federation (the)"],
    [CountryAlpha2.RW, "Rwanda"],
    [CountryAlpha2.SA, "Saudi Arabia"],
    [CountryAlpha2.SB, "Solomon Islands"],
    [CountryAlpha2.SC, "Seychelles"],
    [CountryAlpha2.SD, "Sudan (the)"],
    [CountryAlpha2.SE, "Sweden"],
    [CountryAlpha2.SG, "Singapore"],
    [CountryAlpha2.SH, "Saint Helena, Ascension and Tristan da Cunha"],
    [CountryAlpha2.SI, "Slovenia"],
    [CountryAlpha2.SJ, "Svalbard and Jan Mayen"],
    [CountryAlpha2.SK, "Slovakia"],
    [CountryAlpha2.SL, "Sierra Leone"],
    [CountryAlpha2.SM, "San Marino"],
    [CountryAlpha2.SN, "Senegal"],
    [CountryAlpha2.SO, "Somalia"],
    [CountryAlpha2.SR, "Suriname"],
    [CountryAlpha2.SS, "South Sudan"],
    [CountryAlpha2.ST, "Sao Tome and Principe"],
    [CountryAlpha2.SV, "El Salvador"],
    [CountryAlpha2.SX, "Sint Maarten (Dutch part)"],
    [CountryAlpha2.SY, "Syrian Arab Republic"],
    [CountryAlpha2.SZ, "Eswatini"],
    [CountryAlpha2.TC, "Turks and Caicos Islands (the)"],
    [CountryAlpha2.TD, "Chad"],
    [CountryAlpha2.TF, "French Southern Territories (the)"],
    [CountryAlpha2.TG, "Togo"],
    [CountryAlpha2.TH, "Thailand"],
    [CountryAlpha2.TJ, "Tajikistan"],
    [CountryAlpha2.TK, "Tokelau"],
    [CountryAlpha2.TL, "Timor-Leste"],
    [CountryAlpha2.TM, "Turkmenistan"],
    [CountryAlpha2.TN, "Tunisia"],
    [CountryAlpha2.TO, "Tonga"],
    [CountryAlpha2.TR, "Turkey"],
    [CountryAlpha2.TT, "Trinidad and Tobago"],
    [CountryAlpha2.TV, "Tuvalu"],
    [CountryAlpha2.TW, "Taiwan"],
    [CountryAlpha2.TZ, "Tanzania, United Republic of"],
    [CountryAlpha2.UA, "Ukraine"],
    [CountryAlpha2.UG, "Uganda"],
    [CountryAlpha2.UM, "United States Minor Outlying Islands (the)"],
    [CountryAlpha2.US, "United States of America (the)"],
    [CountryAlpha2.UY, "Uruguay"],
    [CountryAlpha2.UZ, "Uzbekistan"],
    [CountryAlpha2.VA, "Holy See (the)"],
    [CountryAlpha2.VC, "Saint Vincent and the Grenadines"],
    [CountryAlpha2.VE, "Venezuela (Bolivarian Republic of)"],
    [CountryAlpha2.VG, "Virgin Islands (British)"],
    [CountryAlpha2.VI, "Virgin Islands (U.S.)"],
    [CountryAlpha2.VN, "Viet Nam"],
    [CountryAlpha2.VU, "Vanuatu"],
    [CountryAlpha2.WF, "Wallis and Futuna"],
    [CountryAlpha2.WS, "Samoa"],
    [CountryAlpha2.YE, "Yemen"],
    [CountryAlpha2.YT, "Mayotte"],
    [CountryAlpha2.ZA, "South Africa"],
    [CountryAlpha2.ZM, "Zambia"],
    [CountryAlpha2.ZW, "Zimbabwe"]
]);
