/* eslint-disable @typescript-eslint/naming-convention */
// ISO 639-1

export enum LanguageISO639 {
    aa = "aa",
    ab = "ab",
    ae = "ae",
    af = "af",
    ak = "ak",
    am = "am",
    an = "an",
    ar = "ar",
    as = "as",
    av = "av",
    ay = "ay",
    az = "az",
    ba = "ba",
    be = "be",
    bg = "bg",
    bi = "bi",
    bm = "bm",
    bn = "bn",
    bo = "bo",
    br = "br",
    bs = "bs",
    ca = "ca",
    ce = "ce",
    ch = "ch",
    co = "co",
    cr = "cr",
    cs = "cs",
    cu = "cu",
    cv = "cv",
    cy = "cy",
    da = "da",
    de = "de",
    dv = "dv",
    dz = "dz",
    ee = "ee",
    el = "el",
    en = "en",
    eo = "eo",
    es = "es",
    et = "et",
    eu = "eu",
    fa = "fa",
    ff = "ff",
    fi = "fi",
    fj = "fj",
    fo = "fo",
    fr = "fr",
    fy = "fy",
    ga = "ga",
    gd = "gd",
    gl = "gl",
    gn = "gn",
    gu = "gu",
    gv = "gv",
    ha = "ha",
    he = "he",
    hi = "hi",
    ho = "ho",
    hr = "hr",
    ht = "ht",
    hu = "hu",
    hy = "hy",
    hz = "hz",
    ia = "ia",
    id = "id",
    ie = "ie",
    ig = "ig",
    ii = "ii",
    ik = "ik",
    io = "io",
    is = "is",
    it = "it",
    iu = "iu",
    ja = "ja",
    jv = "jv",
    ka = "ka",
    kg = "kg",
    ki = "ki",
    kj = "kj",
    kk = "kk",
    kl = "kl",
    km = "km",
    kn = "kn",
    ko = "ko",
    kr = "kr",
    ks = "ks",
    ku = "ku",
    kv = "kv",
    kw = "kw",
    ky = "ky",
    la = "la",
    lb = "lb",
    lg = "lg",
    li = "li",
    ln = "ln",
    lo = "lo",
    lt = "lt",
    lu = "lu",
    lv = "lv",
    mg = "mg",
    mh = "mh",
    mi = "mi",
    mk = "mk",
    ml = "ml",
    mn = "mn",
    mr = "mr",
    ms = "ms",
    mt = "mt",
    my = "my",
    na = "na",
    nb = "nb",
    nd = "nd",
    ne = "ne",
    ng = "ng",
    nl = "nl",
    nn = "nn",
    no = "no",
    nr = "nr",
    nv = "nv",
    ny = "ny",
    oc = "oc",
    oj = "oj",
    om = "om",
    or = "or",
    os = "os",
    pa = "pa",
    pi = "pi",
    pl = "pl",
    ps = "ps",
    pt = "pt",
    qu = "qu",
    rm = "rm",
    rn = "rn",
    ro = "ro",
    ru = "ru",
    rw = "rw",
    sa = "sa",
    sc = "sc",
    sd = "sd",
    se = "se",
    sg = "sg",
    si = "si",
    sk = "sk",
    sl = "sl",
    sm = "sm",
    sn = "sn",
    so = "so",
    sq = "sq",
    sr = "sr",
    ss = "ss",
    st = "st",
    su = "su",
    sv = "sv",
    sw = "sw",
    ta = "ta",
    te = "te",
    tg = "tg",
    th = "th",
    ti = "ti",
    tk = "tk",
    tl = "tl",
    tn = "tn",
    to = "to",
    tr = "tr",
    ts = "ts",
    tt = "tt",
    tw = "tw",
    ty = "ty",
    ug = "ug",
    uk = "uk",
    ur = "ur",
    uz = "uz",
    ve = "ve",
    vi = "vi",
    vo = "vo",
    wa = "wa",
    wo = "wo",
    xh = "xh",
    yi = "yi",
    yo = "yo",
    za = "za",
    zh = "zh",
    zu = "zu"
}

export interface LanguageDefinition {
    code: LanguageISO639;
    name: string;
    nativeName: string;
}

export const LANGUAGES_ISO639_TO_DISPLAY_NAME = new Map<string, LanguageDefinition>([
    [LanguageISO639.aa, { code: LanguageISO639.aa, name: "Afar", nativeName: "Afaraf" }],
    [LanguageISO639.ab, { code: LanguageISO639.ab, name: "Abkhaz", nativeName: "аҧсуа бызшәа" }],
    [LanguageISO639.ae, { code: LanguageISO639.ae, name: "Avestan", nativeName: "avesta" }],
    [LanguageISO639.af, { code: LanguageISO639.af, name: "Afrikaans", nativeName: "Afrikaans" }],
    [LanguageISO639.ak, { code: LanguageISO639.ak, name: "Akan", nativeName: "Akan" }],
    [LanguageISO639.am, { code: LanguageISO639.am, name: "Amharic", nativeName: "አማርኛ" }],
    [LanguageISO639.an, { code: LanguageISO639.an, name: "Aragonese", nativeName: "aragonés" }],
    [LanguageISO639.ar, { code: LanguageISO639.ar, name: "Arabic", nativeName: "اَلْعَرَبِيَّةُ" }],
    [LanguageISO639.as, { code: LanguageISO639.as, name: "Assamese", nativeName: "অসমীয়া" }],
    [LanguageISO639.av, { code: LanguageISO639.av, name: "Avaric", nativeName: "авар мацӀ" }],
    [LanguageISO639.ay, { code: LanguageISO639.ay, name: "Aymara", nativeName: "aymar aru" }],
    [LanguageISO639.az, { code: LanguageISO639.az, name: "Azerbaijani", nativeName: "azərbaycan dili" }],
    [LanguageISO639.ba, { code: LanguageISO639.ba, name: "Bashkir", nativeName: "башҡорт теле" }],
    [LanguageISO639.be, { code: LanguageISO639.be, name: "Belarusian", nativeName: "беларуская мова" }],
    [LanguageISO639.bg, { code: LanguageISO639.bg, name: "Bulgarian", nativeName: "български език" }],
    [LanguageISO639.bi, { code: LanguageISO639.bi, name: "Bislama", nativeName: "Bislama" }],
    [LanguageISO639.bm, { code: LanguageISO639.bm, name: "Bambara", nativeName: "bamanankan" }],
    [LanguageISO639.bn, { code: LanguageISO639.bn, name: "Bengali", nativeName: "বাংলা" }],
    [LanguageISO639.bo, { code: LanguageISO639.bo, name: "Tibetan", nativeName: "བོད་ཡིག" }],
    [LanguageISO639.br, { code: LanguageISO639.br, name: "Breton", nativeName: "brezhoneg" }],
    [LanguageISO639.bs, { code: LanguageISO639.bs, name: "Bosnian", nativeName: "bosanski jezik" }],
    [LanguageISO639.ca, { code: LanguageISO639.ca, name: "Catalan", nativeName: "Català" }],
    [LanguageISO639.ce, { code: LanguageISO639.ce, name: "Chechen", nativeName: "нохчийн мотт" }],
    [LanguageISO639.ch, { code: LanguageISO639.ch, name: "Chamorro", nativeName: "Chamoru" }],
    [LanguageISO639.co, { code: LanguageISO639.co, name: "Corsican", nativeName: "corsu" }],
    [LanguageISO639.cr, { code: LanguageISO639.cr, name: "Cree", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ" }],
    [LanguageISO639.cs, { code: LanguageISO639.cs, name: "Czech", nativeName: "čeština" }],
    [LanguageISO639.cu, { code: LanguageISO639.cu, name: "Old Church Slavonic", nativeName: "ѩзыкъ словѣньскъ" }],
    [LanguageISO639.cv, { code: LanguageISO639.cv, name: "Chuvash", nativeName: "чӑваш чӗлхи" }],
    [LanguageISO639.cy, { code: LanguageISO639.cy, name: "Welsh", nativeName: "Cymraeg" }],
    [LanguageISO639.da, { code: LanguageISO639.da, name: "Danish", nativeName: "dansk" }],
    [LanguageISO639.de, { code: LanguageISO639.de, name: "German", nativeName: "Deutsch" }],
    [LanguageISO639.dv, { code: LanguageISO639.dv, name: "Divehi", nativeName: "ދިވެހި" }],
    [LanguageISO639.dz, { code: LanguageISO639.dz, name: "Dzongkha", nativeName: "རྫོང་ཁ" }],
    [LanguageISO639.ee, { code: LanguageISO639.ee, name: "Ewe", nativeName: "Eʋegbe" }],
    [LanguageISO639.el, { code: LanguageISO639.el, name: "Greek", nativeName: "Ελληνικά" }],
    [LanguageISO639.en, { code: LanguageISO639.en, name: "English", nativeName: "English" }],
    [LanguageISO639.eo, { code: LanguageISO639.eo, name: "Esperanto", nativeName: "Esperanto" }],
    [LanguageISO639.es, { code: LanguageISO639.es, name: "Spanish", nativeName: "Español" }],
    [LanguageISO639.et, { code: LanguageISO639.et, name: "Estonian", nativeName: "eesti" }],
    [LanguageISO639.eu, { code: LanguageISO639.eu, name: "Basque", nativeName: "euskara" }],
    [LanguageISO639.fa, { code: LanguageISO639.fa, name: "Persian", nativeName: "فارسی" }],
    [LanguageISO639.ff, { code: LanguageISO639.ff, name: "Fula", nativeName: "Fulfulde" }],
    [LanguageISO639.fi, { code: LanguageISO639.fi, name: "Finnish", nativeName: "suomi" }],
    [LanguageISO639.fj, { code: LanguageISO639.fj, name: "Fijian", nativeName: "vosa Vakaviti" }],
    [LanguageISO639.fo, { code: LanguageISO639.fo, name: "Faroese", nativeName: "føroyskt" }],
    [LanguageISO639.fr, { code: LanguageISO639.fr, name: "French", nativeName: "Français" }],
    [LanguageISO639.fy, { code: LanguageISO639.fy, name: "Western Frisian", nativeName: "Frysk" }],
    [LanguageISO639.ga, { code: LanguageISO639.ga, name: "Irish", nativeName: "Gaeilge" }],
    [LanguageISO639.gd, { code: LanguageISO639.gd, name: "Scottish Gaelic", nativeName: "Gàidhlig" }],
    [LanguageISO639.gl, { code: LanguageISO639.gl, name: "Galician", nativeName: "galego" }],
    [LanguageISO639.gn, { code: LanguageISO639.gn, name: "Guaraní", nativeName: "Avañe'ẽ" }],
    [LanguageISO639.gu, { code: LanguageISO639.gu, name: "Gujarati", nativeName: "ગુજરાતી" }],
    [LanguageISO639.gv, { code: LanguageISO639.gv, name: "Manx", nativeName: "Gaelg" }],
    [LanguageISO639.ha, { code: LanguageISO639.ha, name: "Hausa", nativeName: "هَوُسَ" }],
    [LanguageISO639.he, { code: LanguageISO639.he, name: "Hebrew", nativeName: "עברית" }],
    [LanguageISO639.hi, { code: LanguageISO639.hi, name: "Hindi", nativeName: "हिन्दी" }],
    [LanguageISO639.ho, { code: LanguageISO639.ho, name: "Hiri Motu", nativeName: "Hiri Motu" }],
    [LanguageISO639.hr, { code: LanguageISO639.hr, name: "Croatian", nativeName: "Hrvatski" }],
    [LanguageISO639.ht, { code: LanguageISO639.ht, name: "Haitian", nativeName: "Kreyòl ayisyen" }],
    [LanguageISO639.hu, { code: LanguageISO639.hu, name: "Hungarian", nativeName: "magyar" }],
    [LanguageISO639.hy, { code: LanguageISO639.hy, name: "Armenian", nativeName: "Հայերեն" }],
    [LanguageISO639.hz, { code: LanguageISO639.hz, name: "Herero", nativeName: "Otjiherero" }],
    [LanguageISO639.ia, { code: LanguageISO639.ia, name: "Interlingua", nativeName: "Interlingua" }],
    [LanguageISO639.id, { code: LanguageISO639.id, name: "Indonesian", nativeName: "Bahasa Indonesia" }],
    [LanguageISO639.ie, { code: LanguageISO639.ie, name: "Interlingue", nativeName: "Interlingue" }],
    [LanguageISO639.ig, { code: LanguageISO639.ig, name: "Igbo", nativeName: "Asụsụ Igbo" }],
    [LanguageISO639.ii, { code: LanguageISO639.ii, name: "Nuosu", nativeName: "ꆈꌠ꒿ Nuosuhxop" }],
    [LanguageISO639.ik, { code: LanguageISO639.ik, name: "Inupiaq", nativeName: "Iñupiaq" }],
    [LanguageISO639.io, { code: LanguageISO639.io, name: "Ido", nativeName: "Ido" }],
    [LanguageISO639.is, { code: LanguageISO639.is, name: "Icelandic", nativeName: "Íslenska" }],
    [LanguageISO639.it, { code: LanguageISO639.it, name: "Italian", nativeName: "Italiano" }],
    [LanguageISO639.iu, { code: LanguageISO639.iu, name: "Inuktitut", nativeName: "ᐃᓄᒃᑎᑐᑦ" }],
    [LanguageISO639.ja, { code: LanguageISO639.ja, name: "Japanese", nativeName: "日本語" }],
    [LanguageISO639.jv, { code: LanguageISO639.jv, name: "Javanese", nativeName: "basa Jawa" }],
    [LanguageISO639.ka, { code: LanguageISO639.ka, name: "Georgian", nativeName: "ქართული" }],
    [LanguageISO639.kg, { code: LanguageISO639.kg, name: "Kongo", nativeName: "Kikongo" }],
    [LanguageISO639.ki, { code: LanguageISO639.ki, name: "Kikuyu", nativeName: "Gĩkũyũ" }],
    [LanguageISO639.kj, { code: LanguageISO639.kj, name: "Kwanyama", nativeName: "Kuanyama" }],
    [LanguageISO639.kk, { code: LanguageISO639.kk, name: "Kazakh", nativeName: "қазақ тілі" }],
    [LanguageISO639.kl, { code: LanguageISO639.kl, name: "Kalaallisut", nativeName: "kalaallisut" }],
    [LanguageISO639.km, { code: LanguageISO639.km, name: "Khmer", nativeName: "ខេមរភាសា" }],
    [LanguageISO639.kn, { code: LanguageISO639.kn, name: "Kannada", nativeName: "ಕನ್ನಡ" }],
    [LanguageISO639.ko, { code: LanguageISO639.ko, name: "Korean", nativeName: "한국어" }],
    [LanguageISO639.kr, { code: LanguageISO639.kr, name: "Kanuri", nativeName: "Kanuri" }],
    [LanguageISO639.ks, { code: LanguageISO639.ks, name: "Kashmiri", nativeName: "कश्मीरी" }],
    [LanguageISO639.ku, { code: LanguageISO639.ku, name: "Kurdish", nativeName: "Kurdî" }],
    [LanguageISO639.kv, { code: LanguageISO639.kv, name: "Komi", nativeName: "коми кыв" }],
    [LanguageISO639.kw, { code: LanguageISO639.kw, name: "Cornish", nativeName: "Kernewek" }],
    [LanguageISO639.ky, { code: LanguageISO639.ky, name: "Kyrgyz", nativeName: "Кыргызча" }],
    [LanguageISO639.la, { code: LanguageISO639.la, name: "Latin", nativeName: "latine" }],
    [LanguageISO639.lb, { code: LanguageISO639.lb, name: "Luxembourgish", nativeName: "Lëtzebuergesch" }],
    [LanguageISO639.lg, { code: LanguageISO639.lg, name: "Ganda", nativeName: "Luganda" }],
    [LanguageISO639.li, { code: LanguageISO639.li, name: "Limburgish", nativeName: "Limburgs" }],
    [LanguageISO639.ln, { code: LanguageISO639.ln, name: "Lingala", nativeName: "Lingála" }],
    [LanguageISO639.lo, { code: LanguageISO639.lo, name: "Lao", nativeName: "ພາສາລາວ" }],
    [LanguageISO639.lt, { code: LanguageISO639.lt, name: "Lithuanian", nativeName: "lietuvių kalba" }],
    [LanguageISO639.lu, { code: LanguageISO639.lu, name: "Luba-Katanga", nativeName: "Kiluba" }],
    [LanguageISO639.lv, { code: LanguageISO639.lv, name: "Latvian", nativeName: "latviešu valoda" }],
    [LanguageISO639.mg, { code: LanguageISO639.mg, name: "Malagasy", nativeName: "fiteny malagasy" }],
    [LanguageISO639.mh, { code: LanguageISO639.mh, name: "Marshallese", nativeName: "Kajin M̧ajeļ" }],
    [LanguageISO639.mi, { code: LanguageISO639.mi, name: "Māori", nativeName: "te reo Māori" }],
    [LanguageISO639.mk, { code: LanguageISO639.mk, name: "Macedonian", nativeName: "македонски јазик" }],
    [LanguageISO639.ml, { code: LanguageISO639.ml, name: "Malayalam", nativeName: "മലയാളം" }],
    [LanguageISO639.mn, { code: LanguageISO639.mn, name: "Mongolian", nativeName: "Монгол хэл" }],
    [LanguageISO639.mr, { code: LanguageISO639.mr, name: "Marathi", nativeName: "मराठी" }],
    [LanguageISO639.ms, { code: LanguageISO639.ms, name: "Malay", nativeName: "Bahasa Melayu" }],
    [LanguageISO639.mt, { code: LanguageISO639.mt, name: "Maltese", nativeName: "Malti" }],
    [LanguageISO639.my, { code: LanguageISO639.my, name: "Burmese", nativeName: "ဗမာစာ" }],
    [LanguageISO639.na, { code: LanguageISO639.na, name: "Nauru", nativeName: "Dorerin Naoero" }],
    [LanguageISO639.nb, { code: LanguageISO639.nb, name: "Norwegian Bokmål", nativeName: "Norsk bokmål" }],
    [LanguageISO639.nd, { code: LanguageISO639.nd, name: "Northern Ndebele", nativeName: "isiNdebele" }],
    [LanguageISO639.ne, { code: LanguageISO639.ne, name: "Nepali", nativeName: "नेपाली" }],
    [LanguageISO639.ng, { code: LanguageISO639.ng, name: "Ndonga", nativeName: "Owambo" }],
    [LanguageISO639.nl, { code: LanguageISO639.nl, name: "Dutch", nativeName: "Nederlands" }],
    [LanguageISO639.nn, { code: LanguageISO639.nn, name: "Norwegian Nynorsk", nativeName: "Norsk nynorsk" }],
    [LanguageISO639.no, { code: LanguageISO639.no, name: "Norwegian", nativeName: "Norsk" }],
    [LanguageISO639.nr, { code: LanguageISO639.nr, name: "Southern Ndebele", nativeName: "isiNdebele" }],
    [LanguageISO639.nv, { code: LanguageISO639.nv, name: "Navajo", nativeName: "Diné bizaad" }],
    [LanguageISO639.ny, { code: LanguageISO639.ny, name: "Chichewa", nativeName: "chiCheŵa" }],
    [LanguageISO639.oc, { code: LanguageISO639.oc, name: "Occitan", nativeName: "occitan" }],
    [LanguageISO639.oj, { code: LanguageISO639.oj, name: "Ojibwe", nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ" }],
    [LanguageISO639.om, { code: LanguageISO639.om, name: "Oromo", nativeName: "Afaan Oromoo" }],
    [LanguageISO639.or, { code: LanguageISO639.or, name: "Oriya", nativeName: "ଓଡ଼ିଆ" }],
    [LanguageISO639.os, { code: LanguageISO639.os, name: "Ossetian", nativeName: "ирон æвзаг" }],
    [LanguageISO639.pa, { code: LanguageISO639.pa, name: "Panjabi", nativeName: "ਪੰਜਾਬੀ" }],
    [LanguageISO639.pi, { code: LanguageISO639.pi, name: "Pāli", nativeName: "पाऴि" }],
    [LanguageISO639.pl, { code: LanguageISO639.pl, name: "Polish", nativeName: "Polski" }],
    [LanguageISO639.ps, { code: LanguageISO639.ps, name: "Pashto", nativeName: "پښتو" }],
    [LanguageISO639.pt, { code: LanguageISO639.pt, name: "Portuguese", nativeName: "Português" }],
    [LanguageISO639.qu, { code: LanguageISO639.qu, name: "Quechua", nativeName: "Runa Simi" }],
    [LanguageISO639.rm, { code: LanguageISO639.rm, name: "Romansh", nativeName: "rumantsch grischun" }],
    [LanguageISO639.rn, { code: LanguageISO639.rn, name: "Kirundi", nativeName: "Ikirundi" }],
    [LanguageISO639.ro, { code: LanguageISO639.ro, name: "Romanian", nativeName: "Română" }],
    [LanguageISO639.ru, { code: LanguageISO639.ru, name: "Russian", nativeName: "Русский" }],
    [LanguageISO639.rw, { code: LanguageISO639.rw, name: "Kinyarwanda", nativeName: "Ikinyarwanda" }],
    [LanguageISO639.sa, { code: LanguageISO639.sa, name: "Sanskrit", nativeName: "संस्कृतम्" }],
    [LanguageISO639.sc, { code: LanguageISO639.sc, name: "Sardinian", nativeName: "sardu" }],
    [LanguageISO639.sd, { code: LanguageISO639.sd, name: "Sindhi", nativeName: "सिन्धी" }],
    [LanguageISO639.se, { code: LanguageISO639.se, name: "Northern Sami", nativeName: "Davvisámegiella" }],
    [LanguageISO639.sg, { code: LanguageISO639.sg, name: "Sango", nativeName: "yângâ tî sängö" }],
    [LanguageISO639.si, { code: LanguageISO639.si, name: "Sinhala", nativeName: "සිංහල" }],
    [LanguageISO639.sk, { code: LanguageISO639.sk, name: "Slovak", nativeName: "slovenčina" }],
    [LanguageISO639.sl, { code: LanguageISO639.sl, name: "Slovenian", nativeName: "slovenščina" }],
    [LanguageISO639.sm, { code: LanguageISO639.sm, name: "Samoan", nativeName: "gagana fa'a Samoa" }],
    [LanguageISO639.sn, { code: LanguageISO639.sn, name: "Shona", nativeName: "chiShona" }],
    [LanguageISO639.so, { code: LanguageISO639.so, name: "Somali", nativeName: "Soomaaliga" }],
    [LanguageISO639.sq, { code: LanguageISO639.sq, name: "Albanian", nativeName: "Shqip" }],
    [LanguageISO639.sr, { code: LanguageISO639.sr, name: "Serbian", nativeName: "српски језик" }],
    [LanguageISO639.ss, { code: LanguageISO639.ss, name: "Swati", nativeName: "SiSwati" }],
    [LanguageISO639.st, { code: LanguageISO639.st, name: "Southern Sotho", nativeName: "Sesotho" }],
    [LanguageISO639.su, { code: LanguageISO639.su, name: "Sundanese", nativeName: "Basa Sunda" }],
    [LanguageISO639.sv, { code: LanguageISO639.sv, name: "Swedish", nativeName: "Svenska" }],
    [LanguageISO639.sw, { code: LanguageISO639.sw, name: "Swahili", nativeName: "Kiswahili" }],
    [LanguageISO639.ta, { code: LanguageISO639.ta, name: "Tamil", nativeName: "தமிழ்" }],
    [LanguageISO639.te, { code: LanguageISO639.te, name: "Telugu", nativeName: "తెలుగు" }],
    [LanguageISO639.tg, { code: LanguageISO639.tg, name: "Tajik", nativeName: "тоҷикӣ" }],
    [LanguageISO639.th, { code: LanguageISO639.th, name: "Thai", nativeName: "ไทย" }],
    [LanguageISO639.ti, { code: LanguageISO639.ti, name: "Tigrinya", nativeName: "ትግርኛ" }],
    [LanguageISO639.tk, { code: LanguageISO639.tk, name: "Turkmen", nativeName: "Türkmençe" }],
    [LanguageISO639.tl, { code: LanguageISO639.tl, name: "Tagalog", nativeName: "Wikang Tagalog" }],
    [LanguageISO639.tn, { code: LanguageISO639.tn, name: "Tswana", nativeName: "Setswana" }],
    [LanguageISO639.to, { code: LanguageISO639.to, name: "Tonga", nativeName: "faka Tonga" }],
    [LanguageISO639.tr, { code: LanguageISO639.tr, name: "Turkish", nativeName: "Türkçe" }],
    [LanguageISO639.ts, { code: LanguageISO639.ts, name: "Tsonga", nativeName: "Xitsonga" }],
    [LanguageISO639.tt, { code: LanguageISO639.tt, name: "Tatar", nativeName: "татар теле" }],
    [LanguageISO639.tw, { code: LanguageISO639.tw, name: "Twi", nativeName: "Twi" }],
    [LanguageISO639.ty, { code: LanguageISO639.ty, name: "Tahitian", nativeName: "Reo Tahiti" }],
    [LanguageISO639.ug, { code: LanguageISO639.ug, name: "Uyghur", nativeName: "ئۇيغۇرچە‎" }],
    [LanguageISO639.uk, { code: LanguageISO639.uk, name: "Ukrainian", nativeName: "Українська" }],
    [LanguageISO639.ur, { code: LanguageISO639.ur, name: "Urdu", nativeName: "اردو" }],
    [LanguageISO639.uz, { code: LanguageISO639.uz, name: "Uzbek", nativeName: "Ўзбек" }],
    [LanguageISO639.ve, { code: LanguageISO639.ve, name: "Venda", nativeName: "Tshivenḓa" }],
    [LanguageISO639.vi, { code: LanguageISO639.vi, name: "Vietnamese", nativeName: "Tiếng Việt" }],
    [LanguageISO639.vo, { code: LanguageISO639.vo, name: "Volapük", nativeName: "Volapük" }],
    [LanguageISO639.wa, { code: LanguageISO639.wa, name: "Walloon", nativeName: "walon" }],
    [LanguageISO639.wo, { code: LanguageISO639.wo, name: "Wolof", nativeName: "Wollof" }],
    [LanguageISO639.xh, { code: LanguageISO639.xh, name: "Xhosa", nativeName: "isiXhosa" }],
    [LanguageISO639.yi, { code: LanguageISO639.yi, name: "Yiddish", nativeName: "ייִדיש" }],
    [LanguageISO639.yo, { code: LanguageISO639.yo, name: "Yoruba", nativeName: "Yorùbá" }],
    [LanguageISO639.za, { code: LanguageISO639.za, name: "Zhuang", nativeName: "Saɯ cueŋƅ" }],
    [LanguageISO639.zh, { code: LanguageISO639.zh, name: "Chinese", nativeName: "中文" }],
    [LanguageISO639.zu, { code: LanguageISO639.zu, name: "Zulu", nativeName: "isiZulu" }]
]);
