import { IdentityDeletionProcessStartedEventProcessor } from "./IdentityDeletionProcessStartedEventProcessor";

export class IdentityDeletionProcessChangedEventProcessor extends IdentityDeletionProcessStartedEventProcessor {}
