import { Result } from "@js-soft/ts-utils";

/**
 * Type of remote push notification service used
 */
export enum PushServices {
    "apns" = "apns", // eslint-disable-line @typescript-eslint/naming-convention
    "fcm" = "fcm", // eslint-disable-line @typescript-eslint/naming-convention
    "none" = "none" // eslint-disable-line @typescript-eslint/naming-convention
}

/**
 * Get information about the device running the app
 */
export interface INativeDeviceInfoAccess {
    /**
     * Initialize the module to retrieve relevant device information
     */
    init(): Promise<Result<INativeDeviceInfo>>;
    /**
     * Available information about the device running the app
     */
    deviceInfo: INativeDeviceInfo;
}

/**
 * Available information about the device running the app
 */
export interface INativeDeviceInfo {
    /**
     * Value set by the device manufacturer describing the device
     */
    model: string;
    /**
     * Operating system of the device
     */
    platform: string;
    /**
     * Unique identifier of the device generated by the operating system
     */
    uuid: string;
    /**
     * Version of th eoperating system
     */
    version: string;
    /**
     * Manufacturer name of the device
     */
    manufacturer: string;
    /**
     * Indicator whether the device is virtualized in an emulator (and some features like the keychain are not working)
     */
    isVirtual: boolean;
    /**
     * Language used on the operating system
     */
    languageCode: string;
    /**
     * Type of remote push notification service used
     */
    pushService: PushServices;
}
