/* eslint-disable @typescript-eslint/naming-convention */
export enum NativeErrorCodes {
    NOT_IMPLEMENTED_ERROR = "NOT_IMPLEMENTED_ERROR",
    BIOMETRIC_UNKNOWN_ERROR = "BIOMETRIC_UNKNOWN_ERROR",
    BIOMETRIC_UNAVAILABLE = "BIOMETRIC_UNAVAILABLE",
    BIOMETRIC_AUTHENTICATION_FAILED = "BIOMETRIC_AUTHENTICATION_FAILED",
    BIOMETRIC_SDK_NOT_SUPPORTED = "BIOMETRIC_SDK_NOT_SUPPORTED",
    BIOMETRIC_HARDWARE_NOT_SUPPORTED = "BIOMETRIC_HARDWARE_NOT_SUPPORTED",
    BIOMETRIC_PERMISSION_NOT_GRANTED = "BIOMETRIC_PERMISSION_NOT_GRANTED",
    BIOMETRIC_NOT_ENROLLED = "BIOMETRIC_NOT_ENROLLED",
    BIOMETRIC_INTERNAL_PLUGIN_ERROR = "BIOMETRIC_INTERNAL_PLUGIN_ERROR",
    BIOMETRIC_DISMISSED = "BIOMETRIC_DISMISSED",
    BIOMETRIC_PIN_OR_PATTERN_DISMISSED = "BIOMETRIC_PIN_OR_PATTERN_DISMISSED",
    BIOMETRIC_SCREEN_GUARD_UNSECURED = "BIOMETRIC_SCREEN_GUARD_UNSECURED",
    BIOMETRIC_LOCKED_OUT = "BIOMETRIC_LOCKED_OUT",
    BIOMETRIC_LOCKED_OUT_PERMANENT = "BIOMETRIC_LOCKED_OUT_PERMANENT",
    BIOMETRIC_SECRET_NOT_FOUND = "BIOMETRIC_SECRET_NOT_FOUND",
    SCANNER_CANCELLED = "SCANNER_CANCELLED",
    SCANNER_TIMEOUT = "SCANNER_TIMEOUT",
    SCANNER_UNKNOWN = "SCANNER_UNKNOWN",
    KEYCHAIN_UNKNOWN = "KEYCHAIN_UNKNOWN",
    KEYCHAIN_NOT_FOUND = "KEYCHAIN_NOT_FOUND",
    FILESYSTEM_UNKNOWN = "FILESYSTEM_UNKNOWN",
    FILESYSTEM_NOT_FOUND = "FILESYSTEM_NOT_FOUND", // ENOENT
    FILESYSTEM_SECURITY = "FILESYSTEM_SECURITY", // EACCES
    FILESYSTEM_NO_MODIFICATION_ALLOWED = "FILESYSTEM_NO_MODIFICATION_ALLOWED", // EPERM,
    FILESYSTEM_INVALID_MODIFICATION = "FILESYSTEM_INVALID_MODIFICATION", // EISDIR, ENOTDIR, ENOTEMPTY
    FILESYSTEM_PATH_EXISTS = "FILESYSTEM_PATH_EXISTS", // EEXIST
    FILESYSTEM_SELECTION_CANCELLED = "FILESYSTEM_SELECTION_CANCELLED",
    CONFIG_UNKNOWN = "CONFIG_UNKNOWN",
    CONFIG_FILESYSTEM = "CONFIG_FILESYSTEM",
    CONFIG_INIT = "CONFIG_INIT",
    CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND",
    BOOTSTRAP_ALREADY_INITIALIZED = "BOOTSTRAP_ALREADY_INITIALIZED",
    BOOTSTRAP_NOT_INITIALIZED = "BOOTSTRAP_NOT_INITIALIZED",
    THEME_COULD_NOT_BE_APPLIED = "THEME_COULD_NOT_BE_APPLIED",
    NOTIFICATION_UNKNOWN = "NOTIFICATION_UNKNOWN"
}
