name: runtime-oid4vc-tests

services:
  oid4vc-service:
    image: ghcr.io/js-soft/openid4vc-service:3.0.0@sha256:f5d1ff3be85dc049377fd906a59eb20bd00be3a51d06b3e8d369570ac3637819
    ports:
      - "9000:9000"
    platform: linux/amd64
    environment:
      authServer__baseUrl: "https://kc-openid4vc.is.enmeshed.eu/realms/enmeshed-openid4vci"
    volumes:
      - ./service-config.json:/usr/app/config.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb
    networks:
      - default

  connector:
    image: ghcr.io/nmshd/connector:7.4.0-openid4vc.2@sha256:d121f97ce2e4506a7ff58de0012b3445f6d0aeb8dd4d765c09da7f34d8a22b5b
    ports:
      - "8080:80"
    environment:
      CUSTOM_CONFIG_LOCATION: "/config.json"
      transportLibrary__baseUrl: "http://consumer-api:8080"
      transportLibrary__platformClientId: test
      transportLibrary__platformClientSecret: test
      transportLibrary__addressGenerationHostnameOverride: localhost
      database__connectionString: mongodb://root:example@mongodb:27017
      infrastructure__httpServer__authentication__apiKey__keys__default__key: aVeryCoolApiKeyWith30CharactersOr+
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb
    networks:
      - default
      - local-test-backbone

  mongodb:
    image: mongo@sha256:c23684919810f0341e58744987e4b1c510fb8becdae850217d2d04b6fa7605e7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - default

  eudiplo:
    image: ghcr.io/openwallet-foundation-labs/eudiplo:1.16.0
    environment:
      - PUBLIC_URL=http://host.docker.internal:3000
    ports:
      - "3000:3000"
    volumes:
      - ./eudiplo-assets:/app/config

networks:
  default:
    name: runtime-oid4vc-tests-network
  local-test-backbone:
    name: local-test-backbone
    external: true
