name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: bash .ci/runChecks.sh

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build:ci --workspaces
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          COMMIT_HASH: ${{ github.sha }}
          VERSION: ${{ github.ref_name }}
      - run: bash .ci/publishNpm.sh
        env:
          VERSION: ${{ github.ref_name }}
    needs: ["run-checks"]
